version: "3.8"

services:
  books-dg:
    image: postgres:17.2
    volumes:
      - .data:/var/lib/postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres

    ports:
      - 5433:5432

  booksApp:
    image: books_app
    build:
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: r2dbc:postgresql://books-dg:5433/postgres
    ports:
      - 8080:8080
    depends_on:
      - books-dg
