spring.r2dbc.url=r2dbc:postgresql://localhost:5432/postgres
spring.r2dbc.username=root
spring.r2dbc.password=123
spring.data.r2dbc.repositories.enabled=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html

#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database=postgresql
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update