spring:
  r2dbc:
    url: r2dbc:postgresql://books-dg:5432/postgres
    username: root
    password: 123
  liquibase:
    url: jdbc:postgresql://books-dg:5432/postgres
    user: root
    password: 123
    enabled: true
    change-log: classpath:db/changelog_2/db.changelog-master.xml
